<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Excepciones en C++</title>

    <link rel="alternate" href="https://campusempresa.com/cplusplus/exception-handling" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/cplusplus/exception-handling" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/cplusplus/exception-handling" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Construyendo la sociedad de hoy y del mañana</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
										<a href="https://enterprisecampus.net/cplusplus/exception-handling" class="px-2">EN</a></b>
				|
				<b class="px-2">ES</b>
				|
				<a href="https://campusempresa.cat/cplusplus/exception-handling" class="px-2">CA</a>
								</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">El Proyecto</a>
				<a href="/about">Sobre nosotros</a>
				<a href="/contribute">Contribuir</a>
				<a href="/donate">Donaciones</a>
				<a href="/licence">Licencia</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='row navigation'>
	<div class='col-4'>
					<a href='templates'>&#x25C4;Plantillas</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Manejo de Excepciones en C++</a>
	</div>
	<div class='col-4 text-end'>
					<a href='file-io'>Entrada/Salida de Archivos &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>Introducción al Manejo de Excepciones</h1>
<div class='content'><p>El manejo de excepciones es un aspecto crucial del desarrollo de software robusto. Permite que un programa maneje situaciones inesperadas (excepciones) de manera elegante, en lugar de colapsar o producir resultados incorrectos.</p>
</div><h2>Conceptos Clave</h2>
<div class='content'><ul>
<li><strong>Excepción</strong>: Un evento que interrumpe el flujo normal del programa.</li>
<li><strong>Bloque Try</strong>: Un bloque de código que se prueba para detectar excepciones.</li>
<li><strong>Bloque Catch</strong>: Un bloque de código que maneja la excepción.</li>
<li><strong>Sentencia Throw</strong>: Utilizada para señalar la ocurrencia de una excepción.</li>
</ul>
</div><h1>Manejo Básico de Excepciones</h1>
<div class='content'></div><h2>Bloques Try y Catch</h2>
<div class='content'><p>En C++, las excepciones se manejan utilizando bloques <code>try</code> y <code>catch</code>. El bloque <code>try</code> contiene el código que podría lanzar una excepción, y el bloque <code>catch</code> contiene el código para manejar la excepción.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIGludCBudW0xID0gMTA7CiAgICAgICAgaW50IG51bTIgPSAwOwogICAgICAgIGlmIChudW0yID09IDApIHsKICAgICAgICAgICAgdGhyb3cgIsKhRXJyb3IgZGUgZGl2aXNpw7NuIHBvciBjZXJvISI7CiAgICAgICAgfQogICAgICAgIGNvdXQgPDwgbnVtMSAvIG51bTIgPDwgZW5kbDsKICAgIH0gY2F0Y2ggKGNvbnN0IGNoYXIqIGUpIHsKICAgICAgICBjb3V0IDw8ICJFeGNlcGNpw7NuOiAiIDw8IGUgPDwgZW5kbDsKICAgIH0KICAgIHJldHVybiAwOwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        int num1 = 10;
        int num2 = 0;
        if (num2 == 0) {
            throw &quot;&iexcl;Error de divisi&oacute;n por cero!&quot;;
        }
        cout &lt;&lt; num1 / num2 &lt;&lt; endl;
    } catch (const char* e) {
        cout &lt;&lt; &quot;Excepci&oacute;n: &quot; &lt;&lt; e &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'><p>En este ejemplo:</p>
<ul>
<li>El bloque <code>try</code> contiene código que podría lanzar una excepción.</li>
<li>La sentencia <code>throw</code> lanza una excepción si <code>num2</code> es cero.</li>
<li>El bloque <code>catch</code> captura la excepción y la maneja imprimiendo un mensaje de error.</li>
</ul>
</div><h1>Lanzamiento de Excepciones</h1>
<div class='content'><p>Puedes lanzar excepciones de cualquier tipo, incluyendo tipos integrados y tipos definidos por el usuario.</p>
</div><h2>Lanzamiento de Tipos Integrados</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IDQwNDsKICAgIH0gY2F0Y2ggKGludCBlKSB7CiAgICAgICAgY291dCA8PCAiRXhjZXBjacOzbjogQ8OzZGlnbyBkZSBlcnJvciAiIDw8IGUgPDwgZW5kbDsKICAgIH0KICAgIHJldHVybiAwOwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        throw 404;
    } catch (int e) {
        cout &lt;&lt; &quot;Excepci&oacute;n: C&oacute;digo de error &quot; &lt;&lt; e &lt;&lt; endl;
    }
    return 0;
}</pre></div><h2>Lanzamiento de Tipos Definidos por el Usuario</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKY2xhc3MgTXlFeGNlcHRpb24gewpwdWJsaWM6CiAgICBjb25zdCBjaGFyKiB3aGF0KCkgY29uc3QgewogICAgICAgIHJldHVybiAiwqFPY3VycmnDsyB1bmEgZXhjZXBjacOzbiBwZXJzb25hbGl6YWRhISI7CiAgICB9Cn07CgppbnQgbWFpbigpIHsKICAgIHRyeSB7CiAgICAgICAgdGhyb3cgTXlFeGNlcHRpb24oKTsKICAgIH0gY2F0Y2ggKE15RXhjZXB0aW9uJiBlKSB7CiAgICAgICAgY291dCA8PCAiRXhjZXBjacOzbjogIiA8PCBlLndoYXQoKSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

class MyException {
public:
    const char* what() const {
        return &quot;&iexcl;Ocurri&oacute; una excepci&oacute;n personalizada!&quot;;
    }
};

int main() {
    try {
        throw MyException();
    } catch (MyException&amp; e) {
        cout &lt;&lt; &quot;Excepci&oacute;n: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h1>Múltiples Bloques Catch</h1>
<div class='content'><p>Puedes tener múltiples bloques <code>catch</code> para manejar diferentes tipos de excepciones.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IDMuMTQ7CiAgICB9IGNhdGNoIChpbnQgZSkgewogICAgICAgIGNvdXQgPDwgIkNhcHR1csOzIHVuIGVudGVybzogIiA8PCBlIDw8IGVuZGw7CiAgICB9IGNhdGNoIChkb3VibGUgZSkgewogICAgICAgIGNvdXQgPDwgIkNhcHR1csOzIHVuIGRvYmxlOiAiIDw8IGUgPDwgZW5kbDsKICAgIH0gY2F0Y2ggKC4uLikgewogICAgICAgIGNvdXQgPDwgIkNhcHR1csOzIHVuYSBleGNlcGNpw7NuIGRlc2Nvbm9jaWRhLiIgPDwgZW5kbDsKICAgIH0KICAgIHJldHVybiAwOwp9"))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

int main() {
    try {
        throw 3.14;
    } catch (int e) {
        cout &lt;&lt; &quot;Captur&oacute; un entero: &quot; &lt;&lt; e &lt;&lt; endl;
    } catch (double e) {
        cout &lt;&lt; &quot;Captur&oacute; un doble: &quot; &lt;&lt; e &lt;&lt; endl;
    } catch (...) {
        cout &lt;&lt; &quot;Captur&oacute; una excepci&oacute;n desconocida.&quot; &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'><p>En este ejemplo:</p>
<ul>
<li>Los bloques <code>catch</code> manejan diferentes tipos de excepciones.</li>
<li>El bloque <code>catch(...)</code> es un manejador de captura general para cualquier tipo de excepción no capturada por los manejadores anteriores.</li>
</ul>
</div><h1>Clases de Excepción Estándar</h1>
<div class='content'><p>C++ proporciona un conjunto de clases de excepción estándar definidas en el encabezado <code>&lt;stdexcept&gt;</code>.</p>
</div><h2>Excepciones Estándar Comunes</h2>
<div class='content'><p>| Clase de Excepción | Descripción |
|--------------------|-------------|
| <code>std::exception</code> | Clase base para todas las excepciones estándar |
| <code>std::runtime_error</code> | Representa errores en tiempo de ejecución |
| <code>std::logic_error</code> | Representa errores lógicos |
| <code>std::out_of_range</code> | Se lanza cuando ocurre un error fuera de rango |
| <code>std::invalid_argument</code> | Se lanza cuando se pasa un argumento inválido |</p>
</div><h2>Uso de Excepciones Estándar</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8c3RkZXhjZXB0Pgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKaW50IG1haW4oKSB7CiAgICB0cnkgewogICAgICAgIHRocm93IHJ1bnRpbWVfZXJyb3IoIk9jdXJyacOzIHVuIGVycm9yIGVuIHRpZW1wbyBkZSBlamVjdWNpw7NuIik7CiAgICB9IGNhdGNoIChydW50aW1lX2Vycm9yJiBlKSB7CiAgICAgICAgY291dCA8PCAiRXhjZXBjacOzbjogIiA8PCBlLndoYXQoKSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

int main() {
    try {
        throw runtime_error(&quot;Ocurri&oacute; un error en tiempo de ejecuci&oacute;n&quot;);
    } catch (runtime_error&amp; e) {
        cout &lt;&lt; &quot;Excepci&oacute;n: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h1>Manejo Avanzado de Excepciones</h1>
<div class='content'></div><h2>Clases de Excepción Personalizadas</h2>
<div class='content'><p>Puedes crear tus propias clases de excepción heredando de <code>std::exception</code>.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgojaW5jbHVkZSA8ZXhjZXB0aW9uPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKY2xhc3MgTXlFeGNlcHRpb24gOiBwdWJsaWMgZXhjZXB0aW9uIHsKcHVibGljOgogICAgY29uc3QgY2hhciogd2hhdCgpIGNvbnN0IG5vZXhjZXB0IG92ZXJyaWRlIHsKICAgICAgICByZXR1cm4gIk1pIGV4Y2VwY2nDs24gcGVyc29uYWxpemFkYSI7CiAgICB9Cn07CgppbnQgbWFpbigpIHsKICAgIHRyeSB7CiAgICAgICAgdGhyb3cgTXlFeGNlcHRpb24oKTsKICAgIH0gY2F0Y2ggKE15RXhjZXB0aW9uJiBlKSB7CiAgICAgICAgY291dCA8PCAiRXhjZXBjacOzbjogIiA8PCBlLndoYXQoKSA8PCBlbmRsOwogICAgfQogICAgcmV0dXJuIDA7Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
#include &lt;exception&gt;
using namespace std;

class MyException : public exception {
public:
    const char* what() const noexcept override {
        return &quot;Mi excepci&oacute;n personalizada&quot;;
    }
};

int main() {
    try {
        throw MyException();
    } catch (MyException&amp; e) {
        cout &lt;&lt; &quot;Excepci&oacute;n: &quot; &lt;&lt; e.what() &lt;&lt; endl;
    }
    return 0;
}</pre></div><div class='content'></div><h2>Especificaciones de Excepción (Obsoleto)</h2>
<div class='content'><p>Las especificaciones de excepción se utilizaban para especificar qué excepciones podría lanzar una función, pero están obsoletas en C++11 y eliminadas en C++17.</p>
</div><h2>Especificador noexcept</h2>
<div class='content'><p>El especificador <code>noexcept</code> indica que una función no lanza ninguna excepción.</p>
</div><div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("I2luY2x1ZGUgPGlvc3RyZWFtPgp1c2luZyBuYW1lc3BhY2Ugc3RkOwoKdm9pZCBzYWZlRnVuY3Rpb24oKSBub2V4Y2VwdCB7CiAgICBjb3V0IDw8ICJFc3RhIGZ1bmNpw7NuIGdhcmFudGl6YSBubyBsYW56YXIgZXhjZXBjaW9uZXMuIiA8PCBlbmRsOwp9CgppbnQgbWFpbigpIHsKICAgIHNhZmVGdW5jdGlvbigpOwogICAgcmV0dXJuIDA7Cn0="))));alert("¡Copiado!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>#include &lt;iostream&gt;
using namespace std;

void safeFunction() noexcept {
    cout &lt;&lt; &quot;Esta funci&oacute;n garantiza no lanzar excepciones.&quot; &lt;&lt; endl;
}

int main() {
    safeFunction();
    return 0;
}</pre></div><div class='content'></div><h1>Conclusión</h1>
<div class='content'><p>El manejo de excepciones en C++ es una característica poderosa que ayuda a crear programas robustos y resistentes a errores. Al usar <code>try</code>, <code>catch</code> y <code>throw</code>, puedes manejar errores de manera elegante. Comprender las clases de excepción estándar y crear excepciones personalizadas mejora aún más tu capacidad para manejar errores de manera efectiva. Recuerda usar el especificador <code>noexcept</code> para funciones que garantizan no lanzar excepciones, mejorando la fiabilidad y el rendimiento del código.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='templates'>&#x25C4;Plantillas</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Manejo de Excepciones en C++</a>
	</div>
	<div class='col-4 text-end'>
					<a href='file-io'>Entrada/Salida de Archivos &#x25BA;</a>
			</div>
</div>
</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Publicidad</h1>
			<p>Este espacio está destinado a publicidad.</p>
			<p>Si quieres ser patrocinador, contáctanos para incluir enlaces en esta zona: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>¡Gracias por colaborar!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. Todos los derechos reservados</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="/cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
